### PR TITLE
#77 - CookieYes Integration to fix template

### LINKED ISSUE #77: CookieYes Compatibility: Adding \ character in front of / character in template codes
I using CookieYes plugin. It paste template like this:

`<script id="ckyBannerTemplate" type="text/template"><div class="cky-overlay cky-hide"></div></script>`

In the index.html files Simply Static created, this code turns into:

`<script id="ckyBannerTemplate" type="text/template"><div class="cky-overlay cky-hide"><\/div></script>`

There are many <\/ pattern in this template. CookieYes takes this template and pastes it somewhere and the code doesn't work. 

As a solution, I find all index.html files in the generated directory and change <\/ to </ in them.

### PR DESCRIPTION
**Pull request by igorbenic**
Closes #77 

### What's done

Adding a CookieYes integration to target only the CookieYes Banner script template.

### Test

- [ ] Have the CookieYes plugin installed
- [ ] Generate static site
- [ ] Search for id="ckyBannerTemplate" to see if the tag is fine and without <\/div or similar HTML.

### CODE REVIEW

File: src/class-integrations.php [hunk 1]
```diff
@@ -40,5 +41,6 @@ public function includes() {
         require_once $path . 'class-aio-seo-integration.php';
         require_once $path . 'class-seopress-integration.php';
         require_once $path . 'class-elementor-integration.php';
+        require_once $path . 'class-cookieyes-integration.php';
```
Comment (mebius0) [inline src/class-integrations.php:44]: The "i" in the file name isn't capitalized, so updating it will cause an error.
